# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Concerning Scala, Data Science & all things Functional
email: m.sumner91@hotmail.co.uk
description: A blog about my experiences in the world of Functional Programming and Data Science.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://msumner91.github.io" # the base hostname & protocol for your site
twitter_username: msumner91
github_username:  msumner91

# Build settings
markdown: kramdown
